apiVersion: apps/v1
kind: Deployment

metadata:
  name: reverse-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: reverse-app

  template:
    metadata:
      labels:
        app: reverse-app

    spec:
      containers:
      - name: reverse-container
        image: swatikadam16/node-reverse-proxy:latest

        ports:
        - containerPort: 3000